let Categories_Data = [
    { "category_ID": 1, address: { profile: 'http://beacongameserver.ir/images/1.png' }, title: "ایرانی و سنتی" ,catTitle: 'R&F' },
    { "category_ID": 2, address: { profile: 'http://beacongameserver.ir/images/2.png' }, title: "ایتالیای و ملل" , catTitle: 'R&F'},
    { "category_ID": 3, address: { profile: 'http://beacongameserver.ir/images/3.png' }, title: "فست فود" , catTitle: 'R&F'},
    { "category_ID": 4, address: { profile: 'http://beacongameserver.ir/images/4.png' }, title: "سفره خانه" , catTitle: 'R&F'},
    { "category_ID": 5, address: { profile: 'http://beacongameserver.ir/images/5.png' }, title: "بوفه", catTitle: 'R&F' },
    { "category_ID": 6, address: { profile: 'http://beacongameserver.ir/images/6.png' }, title: "کافی شاپ", catTitle: 'R&F' },
    { "category_ID": 7, address: { profile: 'http://beacongameserver.ir/images/7.png' }, title: "صبحانه", catTitle: 'R&F' },
    { "category_ID": 8, address: { profile: 'http://beacongameserver.ir/images/8.png' }, title: "کترینگ" , catTitle: 'R&F'},
    { "category_ID": 9, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "تورهای مسافرتی", catTitle: 'T&S' },
    { "category_ID": 10, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "هتل و اقامتگاه" , catTitle: 'T&S'},
    { "category_ID": 11, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "شهربازی و مراکز تفریحی", catTitle: 'T&S' },
    { "category_ID": 12, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "بازی گروهی و زمین بازی", catTitle: 'T&S' },
    { "category_ID": 13, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "استخر و ورزش های آبی" , catTitle: 'T&S'},
    { "category_ID": 14, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "ورزش های هوایی" , catTitle: 'T&S'},
    { "category_ID": 15, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "باشگاه ورزشی" , catTitle: 'T&S'},
    { "category_ID": 16, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "لیزر موهای زائد", catTitle: 'H&M' },
    { "category_ID": 17, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "ژل و بوتاکس", catTitle: 'H&M' },
    { "category_ID": 18, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "خدمات تناسب اندام و لاغری", catTitle: 'H&M' },
    { "category_ID": 19, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "ماساژ", catTitle: 'H&M' },
    { "category_ID": 20, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "پوست و زیبایی", catTitle: 'H&M' },
    { "category_ID": 21, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "خدمات دندانپزشکی" , catTitle: 'H&M'},
    { "category_ID": 22, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "نمایشی و فرهنگی", catTitle: 'A&T' },
    { "category_ID": 23, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "آتلیه و خدمات چاپ", catTitle: 'A&T' },
    { "category_ID": 24, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "تئاتر", catTitle: 'A&T' },
    { "category_ID": 25, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "کنسرت", catTitle: 'A&T' },
    { "category_ID": 26, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "سینما" , catTitle: 'A&T'},
    { "category_ID": 27, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "کامپیوتر", catTitle: 'E' },
    { "category_ID": 28, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "موسیقی", catTitle: 'E' },
    { "category_ID": 29, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "آشپزی", catTitle: 'E' },
    { "category_ID": 30, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "زبان های خارجی", catTitle: 'E' },
    { "category_ID": 31, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "گردهمایی و همایش", catTitle: 'E' },
    { "category_ID": 32, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "هنر", catTitle: 'E' },
    { "category_ID": 33, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "حسابداری", catTitle: 'E' },
    { "category_ID": 34, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "مهارت های فردی", catTitle: 'E' },
    { "category_ID": 35, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "آرایش مو و صورت" , catTitle: 'B'},
    { "category_ID": 36, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "خدمات ناخن", catTitle: 'B' },
    { "category_ID": 37, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "خدمات پوست" , catTitle: 'B'},
    { "category_ID": 38, address: { profile: 'http://beacongameserver.ir/images/a.png' }, title: "اپیلاسیون", catTitle: 'B' },
];
export default Categories_Data;
